{
implementation: function for ODS zip (delphi)

}

{
function SaveXmlssToODFS(var XMLSS: TZEXMLSS; FileName: string; const SheetsNumbers:array of integer;
                         const SheetsNames: array of string; TextConverter: TAnsiToCPConverter; CodePageName: string; BOM: ansistring = ''): integer; overload;
begin

end; //SaveXmlssToODFS

function ReadODFS(var XMLSS: TZEXMLSS; FileName: string): integer;
begin
end; //ReadODFS
}
